= Metanorma Tools

image:https://img.shields.io/gem/v/metanorma-tools.svg["Gem Version", link="https://rubygems.org/gems/metanorma-tools"]
image:https://github.com/metanorma/metanorma-tools/actions/workflows/rake.yml/badge.svg["Windows Build Status", link="https://github.com/metanorma/metanorma-tools/actions/workflows/rake.yml"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-tools.svg["Pull Requests", link="https://github.com/metanorma/metanorma-tools/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-tools/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-tools/releases"]

== Purpose

Metanorma Tools is a command-line interface that supports the standards
development lifecycle for various SDOs (Standards Development Organizations) to
facilitate the production, packaging and delivery of Metanorma documents.

The post-compilation steps work on Metanorma Presentation XML output
(`*.presentation.xml`).


== Features

The gem provides workflow tools for:

ISO (International Organization for Standardization)::

** link:docs/figure-extraction.adoc[ISO figure package]: export images with ISO
DRG compliant filenames into a package from Metanorma PXML
+
NOTE: The ISO DRG publishes the
https://www.iso.org/drafting-standards.html[DRG Directives]
that defines guidelines for the production of drawing files.

** Comment management for ISO comment sheets (planned - integrating `commenter` gem functionality)

** GitHub comment management integration for collaborative review processes (planned)
** Pre-production fetch of ISO documents from the OBP into Metanorma documents (planned)

* [other SDOs when needed...]


== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'metanorma-tools'
----

And then execute:

[source,shell]
----
$ bundle install
----

Or install it yourself as:

[source,shell]
----
$ gem install metanorma-tools
----


== Usage

See the documentation for individual tools:

* link:docs/figure-extraction.adoc[Figure extraction] - Extract embedded
  figures from Metanorma presentation XML files

ISO workflows:

* link:docs/workflows-iso.adoc[ISO workflows and best practices]
* link:docs/iso-drg-filename-guidance.adoc[ISO DRG filename guidance]



== Development notes

The `spec/fixtures/document-en.dis.presentation.xml` file contains sample
Metanorma XML for testing purposes from the
https://github.com/metanorma/mn-samples-iso[mn-samples-iso repository].

== Dependencies

* `lutaml-model`: For structured data modeling
* `nokogiri`: For XML parsing
* `rubyzip`: For ZIP archive creation
* `thor`: For command-line interface

== Copyright

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/BSD-2-Clause[2-Clause BSD License].
