= Metanorma Tools

image:https://img.shields.io/gem/v/metanorma-tools.svg["Gem Version", link="https://rubygems.org/gems/metanorma-tools"]
image:https://github.com/metanorma/metanorma-tools/actions/workflows/rake.yml/badge.svg["Windows Build Status", link="https://github.com/metanorma/metanorma-tools/actions/workflows/rake.yml"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-tools.svg["Pull Requests", link="https://github.com/metanorma/metanorma-tools/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-tools/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-tools/releases"]

== Purpose

=== General

Metanorma Tools is a Ruby gem that supports the lifecycle of standards editing
for various flavors to facilitate pre and post-compilation of Metanorma
documents.

The gem provides tools for:

* Figure extraction from Metanorma presentation XML files with ISO DRG
  compliance
* Comment management for ISO comment sheets (planned - integrating commenter
  gem functionality)
* Pre-production fetch of ISO documents from the OBP into Metanorma documents
  (planned)
* GitHub comment management integration for collaborative review processes
  (planned)
* Support for various Metanorma flavors and document types

=== Currently implemented

* link:docs/figure-extraction.adoc[Figure extraction] - Extract embedded
  figures from Metanorma presentation XML files with ISO DRG compliance
  features

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'metanorma-tools'
----

And then execute:

[source,shell]
----
$ bundle install
----

Or install it yourself as:

[source,shell]
----
$ gem install metanorma-tools
----

== Usage

See the documentation for individual tools:

* link:docs/figure-extraction.adoc[Figure extraction] - Extract embedded
  figures from Metanorma presentation XML files

== Documentation

=== General documentation

* link:docs/figure-extraction.adoc[Figure extraction guide]
* link:docs/iso-drg-filename-guidance.adoc[ISO DRG filename guidance]

=== Organization-specific workflows

* link:docs/workflows-iso.adoc[ISO workflows and best practices]

== ISO standards support

=== General

Metanorma Tools provides comprehensive support for ISO standards editing
workflows.

=== Current ISO features

* Figure extraction with ISO DRG compliance for filename generation
* Metadata extraction from ISO presentation XML documents
* ZIP packaging for ISO figure submission requirements

=== Planned ISO integration

* Comment management - Import/export ISO comment sheets with GitHub integration
* OBP document fetching - Direct integration with ISO Online Browsing Platform

For detailed ISO-specific guidance, see link:docs/workflows-iso.adoc[ISO Workflows].

=== ISO command examples

[example]
====
Extract figures with ISO DRG compliance:

[source,shell]
----
$ metanorma-tools extract-images iso-document.presentation.xml --prefix "ISO-80000-2"
----

Planned: Import ISO comment sheets:

[source,shell]
----
$ metanorma-tools comment import "ISO DIS comments.docx" --output comments.yaml
----

Planned: Fetch ISO documents from OBP:

[source,shell]
----
$ metanorma-tools fetch-iso ISO-80000-2:2019
----
====

== Development notes

The `spec/fixtures/document-en.dis.presentation.xml` file contains sample
Metanorma XML for testing purposes from the
https://github.com/metanorma/mn-samples-iso[mn-samples-iso repository].

== Dependencies

* `lutaml-model`: For structured data modeling
* `nokogiri`: For XML parsing
* `rubyzip`: For ZIP archive creation
* `thor`: For command-line interface

== Copyright

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/BSD-2-Clause[2-Clause BSD License].
