= Figure extraction

== Overview

The figure extraction tool extracts embedded figures from Metanorma presentation
XML files.

The filenames are generated according to the extended
link:docs/iso-drg-filename-guidance.adoc[ISO DRG guidelines].


== How it works

* The input Metanorma presentation XML file is parsed to identify embedded
figures and obtain metadata needed for the naming.

* Each figure is extracted and saved according to the specified output format
and naming conventions.


== Usage

=== Command

Extract figures from a Metanorma presentation XML file:

[source,bash]
----
metanorma-tools extract-images document.presentation.xml
----

When no options are provided, the files will be named according to ISO DRG guidelines.

This generates filenames like:

* `19135-1_ed1fig1.svg`

`-o, --output-dir DIR`::
Output directory for extracted figures (default: under current directory). By
default named using the "document portion" of the DRG filename pattern as the
output directory name.
+
[example]
====
`19135-1_ed1/{image_filenames}`
====

`--prefix PREFIX`::
Filename prefix for extracted figures
+
[example]
====
`{prefix}_fig1.svg`
====

`--zip`::
Create ZIP archive of extracted figures. By default named using the "document
portion" of the DRG filename pattern.
+
[example]
====
`19135-1_ed1.zip`
====

`--retain-original-filenames`::
Keep original filenames from source document. The Metanorma XML
presentation format allows for embedded figures to retain their original
filenames, which can be useful for versioning and tracking changes.
+
[example]
====
`80000-2_ed2fig2_originalname.png`
====



A custom prefix can be specified to follow a specific naming convention (that is
different from the ISO DRG style).

[source,bash]
----
metanorma-tools extract-images document.presentation.xml \
  --prefix "my_prefix" \
  --output-dir figures
----

[example]
====
`figures/my_prefixfig2_originalname.png`
====


To create a figure submission package, use the following command:

[source,bash]
----
metanorma-tools extract-images document.presentation.xml \
  --zip \
  --output-dir submission-figures
----

[example]
====
`submission-figures.zip`
====


== See also

* link:iso-drg-filename-guidance.adoc[ISO DRG filename guidance]
* link:workflows-iso.adoc[ISO workflows and best practices]
